# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crib',
            name='address',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='guest',
            name='address',
            field=models.CharField(max_length=254),
        ),
    ]
