# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0002_auto_20170412_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='crib',
            name='image',
            field=models.ImageField(default='no_image', upload_to=b''),
            preserve_default=False,
        ),
    ]
