# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0003_crib_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crib',
            name='image',
            field=models.ImageField(blank=True, upload_to='cribs/static/cribs_pictures/'),
        ),
    ]
