# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0005_auto_20170413_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cribimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='guest',
            name='image',
            field=models.ImageField(blank=True, upload_to='cribs/static/guest_pictures/'),
        ),
        migrations.AlterField(
            model_name='host',
            name='image',
            field=models.ImageField(blank=True, upload_to='cribs/static/host_pictures/'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
