# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0006_auto_20170416_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crib',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.Host'),
        ),
        migrations.AlterField(
            model_name='cribequipments',
            name='crib_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.AllCribEquipments'),
        ),
        migrations.AlterField(
            model_name='guesthobbies',
            name='guest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.Guest'),
        ),
        migrations.AlterField(
            model_name='guesthobbies',
            name='hobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.AllHobbies'),
        ),
        migrations.AlterField(
            model_name='guestlanguages',
            name='guest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.Guest'),
        ),
        migrations.AlterField(
            model_name='guestlanguages',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.AllStatus'),
        ),
        migrations.AlterField(
            model_name='gueststatus',
            name='guest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.Guest'),
        ),
        migrations.AlterField(
            model_name='gueststatus',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.AllStatus'),
        ),
        migrations.AlterField(
            model_name='hosthobbies',
            name='hobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.AllHobbies'),
        ),
        migrations.AlterField(
            model_name='hosthobbies',
            name='host_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.Host'),
        ),
        migrations.AlterField(
            model_name='hostlanguages',
            name='host_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.Host'),
        ),
        migrations.AlterField(
            model_name='hostlanguages',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.AllStatus'),
        ),
        migrations.AlterField(
            model_name='rents',
            name='crib_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.Crib'),
        ),
        migrations.AlterField(
            model_name='rents',
            name='guest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.Guest'),
        ),
        migrations.AlterField(
            model_name='rents',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.Host'),
        ),
        migrations.AlterField(
            model_name='roomequipments',
            name='room_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.AllRoomEquipments'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.Room'),
        ),
    ]
