# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0008_auto_20170416_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='crib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.Crib'),
        ),
    ]
