# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0009_room_crib'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='lookingForACrib',
            field=models.NullBooleanField(),
        ),
    ]
