# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0010_guest_lookingforacrib'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
