# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0012_auto_20170416_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='crib',
            name='complete_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribs.Address'),
        ),
        migrations.AlterField(
            model_name='crib',
            name='address',
            field=models.CharField(max_length=254),
        ),
    ]
