# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0013_auto_20170416_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crib',
            name='image',
        ),
        migrations.AlterField(
            model_name='cribimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='cribs/static/crib_pictures/'),
        ),
    ]
