# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0015_auto_20170417_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(default=4)),
                ('crib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cribs.Crib')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cribs.Guest')),
            ],
        ),
    ]
